// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// APIEndpointInput - An ApiEndpoint is a description of an Endpoint for an API.
type APIEndpointInput struct {
	// The ID of this ApiEndpoint. This is a hash of the method and path.
	APIEndpointID string `json:"api_endpoint_id"`
	// A detailed description of the ApiEndpoint.
	Description string `json:"description"`
	// A human-readable name for the ApiEndpoint.
	DisplayName string `json:"display_name"`
	// HTTP verb.
	Method string `json:"method"`
	// Path that handles this Api.
	Path string `json:"path"`
	// The version ID of the Api this ApiEndpoint belongs to.
	VersionID string `json:"version_id"`
}

// APIEndpoint - An ApiEndpoint is a description of an Endpoint for an API.
type APIEndpoint struct {
	// The ID of this ApiEndpoint. This is a hash of the method and path.
	APIEndpointID string `json:"api_endpoint_id"`
	// The ID of the Api this ApiEndpoint belongs to.
	APIID string `json:"api_id"`
	// Creation timestamp.
	CreatedAt time.Time `json:"created_at"`
	// A detailed description of the ApiEndpoint.
	Description string `json:"description"`
	// A human-readable name for the ApiEndpoint.
	DisplayName string `json:"display_name"`
	// Determines if the endpoint was found in the OpenAPI spec associated with the parent Api.
	Matched *bool `json:"matched,omitempty"`
	// HTTP verb.
	Method string `json:"method"`
	// Path that handles this Api.
	Path string `json:"path"`
	// Last update timestamp.
	UpdatedAt time.Time `json:"updated_at"`
	// The version ID of the Api this ApiEndpoint belongs to.
	VersionID string `json:"version_id"`
	// The workspace ID this ApiEndpoint belongs to.
	WorkspaceID string `json:"workspace_id"`
}
