// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIKeyCreate - Represents the information needed to create an ApiKey.
type APIKeyCreate struct {
	// The name of the ApiKey.
	Name string `json:"name"`
}
