// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// BoundedRequest - A BoundedRequest is a request that has been logged by the Speakeasy without the contents of the request.
type BoundedRequest struct {
	// The ID of the ApiEndpoint this request was made to.
	APIEndpointID string `json:"api_endpoint_id"`
	// The ID of the Api this request was made to.
	APIID string `json:"api_id"`
	// Creation timestamp.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the customer that made this request.
	CustomerID string `json:"customer_id"`
	// The latency of the request.
	Latency int64 `json:"latency"`
	// Metadata associated with this request
	Metadata []RequestMetadata `json:"metadata,omitempty"`
	// HTTP verb.
	Method string `json:"method"`
	// The path of the request.
	Path string `json:"path"`
	// The time the request finished.
	RequestFinishTime time.Time `json:"request_finish_time"`
	// The ID of this request.
	RequestID string `json:"request_id"`
	// The time the request was made.
	RequestStartTime time.Time `json:"request_start_time"`
	// The status code of the request.
	Status int64 `json:"status"`
	// The version ID of the Api this request was made to.
	VersionID string `json:"version_id"`
	// The workspace ID this request was made to.
	WorkspaceID string `json:"workspace_id"`
}
