// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Error - The `Status` type defines a logical error model
type Error struct {
	// A developer-facing error message.
	Message string `json:"message"`
	// The HTTP status code
	StatusCode int `json:"status_code"`
}
