// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Filter - A filter is a key-value pair that can be used to filter a list of requests.
type Filter struct {
	// The key of the filter.
	Key string `json:"key"`
	// The operator of the filter.
	Operator string `json:"operator"`
	// The value of the filter.
	Value string `json:"value"`
}
