// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GenerateOpenAPISpecDiff - OK
type GenerateOpenAPISpecDiff struct {
	CurrentSchema string `json:"current_schema"`
	NewSchema     string `json:"new_schema"`
}
