// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GenerationConfigurationRequest struct {
	APIKey        string                  `json:"api_key"`
	Configuration GenerationConfiguration `json:"configuration"`
}
