// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PortalSettings - PortalSettings is the description of a workspace's developer experience portal
type PortalSettings struct {
	// The callback URL of the workspace's developer experience portal.
	CallbackURL *string `json:"callback_url,omitempty"`
	// The docs link of the workspace's developer experience portal.
	DocsLink *string `json:"docs_link,omitempty"`
	// Whether the portal is enabled or not.
	Enabled bool `json:"enabled"`
	// The primary color of the workspace's developer experience portal.
	PrimaryColor *string `json:"primary_color,omitempty"`
	// The secondary color of the workspace's developer experience portal.
	SecondaryColor *string `json:"secondary_color,omitempty"`
	// The subdomain of the portal. To get a custom domain, please contact support.
	Subdomain *string `json:"subdomain,omitempty"`
	// The support link of the workspace's developer experience portal.
	SupportLink *string `json:"support_link,omitempty"`
	// The title of the workspace's developer experience portal.
	Title *string `json:"title,omitempty"`
	// The workspace ID this PortalSettings belongs to.
	WorkspaceID string `json:"workspace_id"`
}
