// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SchemaDiffValueChange struct {
	// Represents the previous value of the element.
	From string `json:"From"`
	// Represents the current value of the element.
	To string `json:"To"`
}

// SchemaDiff - A SchemaDiff represents a diff of two Schemas.
type SchemaDiff struct {
	// Holds every addition change in the diff.
	Additions []string `json:"additions"`
	// Holds every deletion change in the diff.
	Deletions []string `json:"deletions"`
	// Holds every modification change in the diff.
	Modifications map[string]SchemaDiffValueChange `json:"modifications"`
}
