// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"speakeasy/internal/sdk/pkg/models/shared"
	"time"
)

func (r *APIResourceModel) RefreshFromCreateResponse(resp *shared.API) {
	r.APIID = types.StringValue(resp.APIID)
	r.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	r.Description = types.StringValue(resp.Description)
	r.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
	r.VersionID = types.StringValue(resp.VersionID)
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)
}
