// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"speakeasy/internal/sdk/pkg/models/shared"
)

func (r *APIKeyResourceModel) ToCreateSDKType() *shared.APIKeyCreate {
	name := r.Name.ValueString()
	out := shared.APIKeyCreate{
		Name: name,
	}
	return &out
}

func (r *APIKeyResourceModel) ToDeleteSDKType() *shared.APIKeyCreate {
	out := r.ToCreateSDKType()
	return out
}

func (r *APIKeyResourceModel) RefreshFromCreateResponse(resp *shared.APIKey) {
	r.ID = types.StringValue(resp.ID)
	r.Key = types.StringValue(resp.Key)
	r.Name = types.StringValue(resp.Name)
	r.WorkspaceID = types.StringValue(resp.WorkspaceID)
}
