// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type GenerationConfiguration struct {
	APIID       types.String `tfsdk:"api_id"`
	IsMonorepo  types.Bool   `tfsdk:"is_monorepo"`
	RepoSetup   types.String `tfsdk:"repo_setup"`
	RepoURL     types.String `tfsdk:"repo_url"`
	SchemaAuth  types.String `tfsdk:"schema_auth"`
	SchemaURL   types.String `tfsdk:"schema_url"`
	VersionID   types.String `tfsdk:"version_id"`
	WorkspaceID types.String `tfsdk:"workspace_id"`
}
