// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type DeleteAPIPathParams struct {
	// The ID of the Api to delete.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to delete.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

type DeleteAPIRequest struct {
	PathParams DeleteAPIPathParams
}

type DeleteAPIResponse struct {
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
