// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type DeletePortalRequest struct {
	// Workspace's ID
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

type DeletePortalResponse struct {
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
