// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteGenerationConfigurationRequest struct {
	APIID     string `pathParam:"style=simple,explode=false,name=apiID"`
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
	// Workspace's ID
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

type DeleteGenerationConfigurationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
