// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type DeletePluginRequest struct {
	// The ID of the plugin to delete.
	PluginID string `pathParam:"style=simple,explode=false,name=pluginID"`
}

type DeletePluginResponse struct {
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
