// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type FindAPIEndpointRequest struct {
	// The ID of the Api the ApiEndpoint belongs to.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The displayName of the ApiEndpoint to find (set by operationId from OpenAPI schema).
	DisplayName string `pathParam:"style=simple,explode=false,name=displayName"`
	// The version ID of the Api the ApiEndpoint belongs to.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

type FindAPIEndpointResponse struct {
	// OK
	APIEndpoint *shared.APIEndpoint
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
