// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

// GetApisOp - Configuration for filter operations
type GetApisOp struct {
	// Whether to AND or OR the filters
	And bool `queryParam:"name=and"`
}

type GetApisQueryParams struct {
	// Metadata to filter Apis on
	Metadata map[string][]string `queryParam:"style=deepObject,explode=true,name=metadata"`
	// Configuration for filter operations
	Op *GetApisOp `queryParam:"style=deepObject,explode=true,name=op"`
}

type GetApisRequest struct {
	QueryParams GetApisQueryParams
}

type GetApisResponse struct {
	// OK
	Apis        []shared.API
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
