// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type GetEmbedAccessTokenRequest struct {
	// The description of the embed access token.
	Description *string `queryParam:"style=form,explode=true,name=description"`
	// The duration (in minutes) of the embed access token.
	Duration *int64 `queryParam:"style=form,explode=true,name=duration"`
	// The filter to apply to the query.
	Filters *shared.Filters `queryParam:"serialization=json,name=filters"`
}

type GetEmbedAccessTokenResponse struct {
	ContentType string
	// OK
	EmbedAccessTokenResponse *shared.EmbedAccessTokenResponse
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
