// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type GetPluginPathParams struct {
	// The ID of the plugin to get.
	PluginID string `pathParam:"style=simple,explode=false,name=pluginID"`
}

type GetPluginRequest struct {
	PathParams GetPluginPathParams
}

type GetPluginResponse struct {
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	Plugin      *shared.Plugin
	StatusCode  int
	RawResponse *http.Response
}
