// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type GetSchemaRevisionPathParams struct {
	// The ID of the Api to retrieve schemas for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The revision ID of the schema to retrieve.
	RevisionID string `pathParam:"style=simple,explode=false,name=revisionID"`
	// The version ID of the Api to delete metadata for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

type GetSchemaRevisionRequest struct {
	PathParams GetSchemaRevisionPathParams
}

type GetSchemaRevisionResponse struct {
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	Schema      *shared.Schema
	StatusCode  int
	RawResponse *http.Response
}
