// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type GetSchemaDiffPathParams struct {
	// The ID of the Api to retrieve schemas for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The base revision ID of the schema to retrieve.
	BaseRevisionID string `pathParam:"style=simple,explode=false,name=baseRevisionID"`
	// The target revision ID of the schema to retrieve.
	TargetRevisionID string `pathParam:"style=simple,explode=false,name=targetRevisionID"`
	// The version ID of the Api to delete metadata for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

type GetSchemaDiffRequest struct {
	PathParams GetSchemaDiffPathParams
}

type GetSchemaDiffResponse struct {
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	SchemaDiff  *shared.SchemaDiff
	StatusCode  int
	RawResponse *http.Response
}
