// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type GetSchemasRequest struct {
	// The ID of the Api to retrieve schemas for.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to delete metadata for.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

type GetSchemasResponse struct {
	ContentType string
	// Default error response
	Error *shared.Error
	// OK
	Schemata    []shared.Schema
	StatusCode  int
	RawResponse *http.Response
}
