// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type ReadAPIRequest struct {
	// The ID of the Api to read.
	APIID string `pathParam:"style=simple,explode=false,name=apiID"`
	// The version ID of the Api to read.
	VersionID string `pathParam:"style=simple,explode=false,name=versionID"`
}

type ReadAPIResponse struct {
	// OK
	API         *shared.API
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
