// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type RevokeAPIKeyRequest struct {
	// The ID of the ApiKey to revoke.
	APIKeyID string `pathParam:"style=simple,explode=false,name=apiKeyID"`
	// The ID of the workspace to revoke the ApiKey for.
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

type RevokeAPIKeyResponse struct {
	ContentType string
	// Default error response
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
