// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type UpsertGenerationConfigurationRequest struct {
	GenerationConfigurationRequest *shared.GenerationConfigurationRequest `request:"mediaType=application/json"`
	APIID                          string                                 `pathParam:"style=simple,explode=false,name=apiID"`
	VersionID                      string                                 `pathParam:"style=simple,explode=false,name=versionID"`
	// Workspace's ID
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

type UpsertGenerationConfigurationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
