// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"speakeasy/internal/sdk/pkg/models/shared"
)

type UpsertPortalRequest struct {
	PortalSettings *shared.PortalSettings `request:"mediaType=application/json"`
	// Workspace's ID
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceID"`
}

type UpsertPortalResponse struct {
	ContentType string
	// Default error response
	Error *shared.Error
	// Workspace's portal settings
	PortalSettings *shared.PortalSettings
	StatusCode     int
	RawResponse    *http.Response
}
